### ISSUE TITLE
[patch] v3.0.0-r1 fails to build with boost-1.57 and later

### ISSUE THREAD

**Issue by ncopa** [mapnik/mapnik#2764]
I got this build failure with Alpine Linux after boost was upgraded to 1.57:
```
python scons/scons.py -j1 --config=cache --implicit-cache --max-drift=1
scons: Reading SConscript files ...
[94mUsing previous successful configuration...[0m
[94mRe-configure by running "python scons/scons.py configure".[0m
[94m
Welcome to Mapnik...
[0m
[91mNotice: dependencies not met for plugin 'ogr', not building...[0m
[91mNotice: dependencies not met for plugin 'gdal', not building...[0m
scons: done reading SConscript files.
scons: Building targets ...
g++ -o plugins/input/geojson/geojson_datasource.os -c -std=c++11 -Wall -Wsign-compare -pthread -ftemplate-depth-300 -Wno-pragmas -O3 -fPIC -DSHAPE_MEMORY_MAPPED_FILE -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -Ideps -Ideps/clipper/include -Ideps/agg/include -Iinclude -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 plugins/input/geojson/geojson_datasource.cpp
In file included from plugins/input/geojson/geojson_datasource.cpp:23:0:
plugins/input/geojson/geojson_datasource.hpp:76:26: error: 'node_s_mem_static_tag' was not declared in this scope
                          node_s_mem_static_tag>;
                          ^
plugins/input/geojson/geojson_datasource.hpp:76:47: error: template argument 6 is invalid
                          node_s_mem_static_tag>;
                                               ^
In file included from /usr/include/boost/geometry/algorithms/detail/closest_feature/range_to_range.hpp:23:0,
                 from /usr/include/boost/geometry/algorithms/detail/distance/range_to_geometry_rtree.hpp:26,
                 from /usr/include/boost/geometry/algorithms/detail/distance/multipoint_to_geometry.hpp:26,
                 from /usr/include/boost/geometry/algorithms/detail/distance/implementation.hpp:25,
                 from /usr/include/boost/geometry/algorithms/detail/comparable_distance/implementation.hpp:22,
                 from /usr/include/boost/geometry/algorithms/comparable_distance.hpp:23,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp:19,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:32,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:29,
                 from /usr/include/boost/geometry/algorithms/buffer.hpp:33,
                 from /usr/include/boost/geometry/geometry.hpp:55,
                 from /usr/include/boost/geometry.hpp:17,
                 from plugins/input/geojson/geojson_datasource.hpp:45,
                 from plugins/input/geojson/geojson_datasource.cpp:23:
/usr/include/boost/geometry/index/rtree.hpp: In instantiation of 'class boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >':
plugins/input/geojson/geojson_datasource.cpp:256:18:   required from here
/usr/include/boost/geometry/index/rtree.hpp:190:68: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename detail::rtree::options_type<Parameters>::type options_type;
                                                                    ^
/usr/include/boost/geometry/index/rtree.hpp:192:127: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef detail::rtree::allocators<allocator_type, value_type, typename options_type::parameters_type, box_type, node_tag> allocators_type;
                                                                                                                               ^
In file included from /usr/include/boost/geometry/algorithms/detail/closest_feature/range_to_range.hpp:23:0,
                 from /usr/include/boost/geometry/algorithms/detail/distance/range_to_geometry_rtree.hpp:26,
                 from /usr/include/boost/geometry/algorithms/detail/distance/multipoint_to_geometry.hpp:26,
                 from /usr/include/boost/geometry/algorithms/detail/distance/implementation.hpp:25,
                 from /usr/include/boost/geometry/algorithms/detail/comparable_distance/implementation.hpp:22,
                 from /usr/include/boost/geometry/algorithms/comparable_distance.hpp:23,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp:19,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:32,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:29,
                 from /usr/include/boost/geometry/algorithms/buffer.hpp:33,
                 from /usr/include/boost/geometry/geometry.hpp:55,
                 from /usr/include/boost/geometry.hpp:17,
                 from plugins/input/geojson/geojson_datasource.hpp:45,
                 from plugins/input/geojson/geojson_datasource.cpp:23:
/usr/include/boost/geometry/index/rtree.hpp:194:137: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename detail::rtree::node<value_type, typename options_type::parameters_type, box_type, allocators_type, node_tag>::type node;
                                                                                                                                         ^
/usr/include/boost/geometry/index/rtree.hpp:195:146: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename detail::rtree::internal_node<value_type, typename options_type::parameters_type, box_type, allocators_type, node_tag>::type internal_node;
                                                                                                                                                  ^
/usr/include/boost/geometry/index/rtree.hpp:196:137: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename detail::rtree::leaf<value_type, typename options_type::parameters_type, box_type, allocators_type, node_tag>::type leaf;
                                                                                                                                         ^
/usr/include/boost/geometry/index/rtree.hpp:198:52: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename allocators_type::node_pointer node_pointer;
                                                    ^
/usr/include/boost/geometry/index/rtree.hpp:200:116: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef detail::rtree::subtree_destroyer<value_type, options_type, translator_type, box_type, allocators_type> subtree_destroyer;
                                                                                                                    ^
/usr/include/boost/geometry/index/rtree.hpp:211:49: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename allocators_type::reference reference;
                                                 ^
/usr/include/boost/geometry/index/rtree.hpp:213:55: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename allocators_type::const_reference const_reference;
                                                       ^
/usr/include/boost/geometry/index/rtree.hpp:215:47: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename allocators_type::pointer pointer;
                                               ^
/usr/include/boost/geometry/index/rtree.hpp:217:53: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename allocators_type::const_pointer const_pointer;
                                                     ^
/usr/include/boost/geometry/index/rtree.hpp:219:55: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename allocators_type::difference_type difference_type;
                                                       ^
/usr/include/boost/geometry/index/rtree.hpp:221:49: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef typename allocators_type::size_type size_type;
                                                 ^
/usr/include/boost/geometry/index/rtree.hpp:224:90: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     typedef index::detail::rtree::iterators::query_iterator<value_type, allocators_type> const_query_iterator;
                                                                                          ^
/usr/include/boost/geometry/index/rtree.hpp:904:5: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     qbegin_(Predicates const& predicates) const
     ^
/usr/include/boost/geometry/index/rtree.hpp:959:5: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     qend_(Predicates const& predicates) const
     ^
/usr/include/boost/geometry/index/rtree.hpp:1012:5: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
     qend_() const
     ^
plugins/input/geojson/geojson_datasource.cpp: In member function 'virtual mapnik::featureset_ptr geojson_datasource::features(const mapnik::query&) const':
plugins/input/geojson/geojson_datasource.cpp:256:20: error: 'class boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >' has no member named 'query'
             tree_->query(boost::geometry::index::intersects(box),std::back_inserter(index_array));
                    ^
In file included from /usr/include/boost/geometry/algorithms/detail/closest_feature/range_to_range.hpp:23:0,
                 from /usr/include/boost/geometry/algorithms/detail/distance/range_to_geometry_rtree.hpp:26,
                 from /usr/include/boost/geometry/algorithms/detail/distance/multipoint_to_geometry.hpp:26,
                 from /usr/include/boost/geometry/algorithms/detail/distance/implementation.hpp:25,
                 from /usr/include/boost/geometry/algorithms/detail/comparable_distance/implementation.hpp:22,
                 from /usr/include/boost/geometry/algorithms/comparable_distance.hpp:23,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/turn_in_piece_visitor.hpp:19,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:32,
                 from /usr/include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:29,
                 from /usr/include/boost/geometry/algorithms/buffer.hpp:33,
                 from /usr/include/boost/geometry/geometry.hpp:55,
                 from /usr/include/boost/geometry.hpp:17,
                 from plugins/input/geojson/geojson_datasource.hpp:45,
                 from plugins/input/geojson/geojson_datasource.cpp:23:
/usr/include/boost/geometry/index/rtree.hpp: In instantiation of 'boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::rtree(const Range&, const parameters_type&, const indexable_getter&, const value_equal&, const allocator_type&) [with Range = std::vector<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; Value = std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>; Parameters = geojson_linear<16ul, 4ul>; IndexableGetter = boost::geometry::index::indexable<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; EqualTo = boost::geometry::index::equal_to<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; Allocator = std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::parameters_type = geojson_linear<16ul, 4ul>; boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::indexable_getter = boost::geometry::index::indexable<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::value_equal = boost::geometry::index::equal_to<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::allocator_type = std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >]':
include/mapnik/make_unique.hpp:36:65:   required from 'std::unique_ptr<T> std::make_unique(Args&& ...) [with T = boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >; Args = {std::vector<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> > >&}]'
plugins/input/geojson/geojson_datasource.cpp:196:56:   required from 'void geojson_datasource::parse_geojson(const T&) [with T = std::basic_string<char>]'
plugins/input/geojson/geojson_datasource.cpp:123:37:   required from here
/usr/include/boost/geometry/index/rtree.hpp:319:107: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
         typedef detail::rtree::pack<value_type, options_type, translator_type, box_type, allocators_type> pack;
                                                                                                           ^
/usr/include/boost/geometry/index/rtree.hpp:322:108: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'allocators'
                                      m_members.parameters(), m_members.translator(), m_members.allocators());
                                                                                                            ^
/usr/include/boost/geometry/index/rtree.hpp:321:24: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'root'
         m_members.root = pack::apply(::boost::begin(rng), ::boost::end(rng), vc, ll,
                        ^
/usr/include/boost/geometry/index/rtree.hpp:323:32: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'values_count'
         m_members.values_count = vc;
                                ^
/usr/include/boost/geometry/index/rtree.hpp:324:31: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'leafs_level'
         m_members.leafs_level = ll;
                               ^
/usr/include/boost/geometry/index/rtree.hpp: In instantiation of 'void boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::raw_destroy(boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>&) [with Value = std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>; Parameters = geojson_linear<16ul, 4ul>; IndexableGetter = boost::geometry::index::indexable<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; EqualTo = boost::geometry::index::equal_to<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; Allocator = std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >]':
/usr/include/boost/geometry/index/rtree.hpp:335:9:   required from 'boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::~rtree() [with Value = std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>; Parameters = geojson_linear<16ul, 4ul>; IndexableGetter = boost::geometry::index::indexable<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; EqualTo = boost::geometry::index::equal_to<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; Allocator = std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >]'
/usr/include/c++/4.9.2/bits/unique_ptr.h:76:2:   required from 'void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >]'
/usr/include/c++/4.9.2/bits/unique_ptr.h:236:16:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >; _Dp = std::default_delete<boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> > >]'
/usr/include/c++/4.9.2/bits/unique_ptr.h:200:61:   required from 'constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr(std::nullptr_t) [with _Tp = boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >; _Dp = std::default_delete<boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> > >; std::nullptr_t = std::nullptr_t]'
plugins/input/geojson/geojson_datasource.cpp:103:18:   required from here
/usr/include/boost/geometry/index/rtree.hpp:1327:9: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'root'
         if ( t.m_members.root )
         ^
/usr/include/boost/geometry/index/rtree.hpp:1330:17: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
                 del_v(t.m_members.root, t.m_members.allocators());
                 ^
/usr/include/boost/geometry/index/rtree.hpp:1330:17: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
/usr/include/boost/geometry/index/rtree.hpp:1331:49: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'root'
             detail::rtree::apply_visitor(del_v, *t.m_members.root);
                                                 ^
/usr/include/boost/geometry/index/rtree.hpp:1333:30: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'root'
             t.m_members.root = 0;
                              ^
/usr/include/boost/geometry/index/rtree.hpp:1335:34: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'values_count'
         t.m_members.values_count = 0;
                                  ^
/usr/include/boost/geometry/index/rtree.hpp:1336:33: error: 'struct boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >::members_holder' has no member named 'leafs_level'
         t.m_members.leafs_level = 0;
                                 ^
/usr/include/boost/geometry/index/rtree.hpp: In instantiation of 'boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::members_holder::members_holder(const IndGet&, const ValEq&, const Parameters&, Alloc&&) [with IndGet = boost::geometry::index::indexable<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; ValEq = boost::geometry::index::equal_to<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; Alloc = const std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >&; Value = std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>; Parameters = geojson_linear<16ul, 4ul>; IndexableGetter = boost::geometry::index::indexable<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; EqualTo = boost::geometry::index::equal_to<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; Allocator = std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >]':
/usr/include/boost/geometry/index/rtree.hpp:317:57:   required from 'boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::rtree(const Range&, const parameters_type&, const indexable_getter&, const value_equal&, const allocator_type&) [with Range = std::vector<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; Value = std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>; Parameters = geojson_linear<16ul, 4ul>; IndexableGetter = boost::geometry::index::indexable<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; EqualTo = boost::geometry::index::equal_to<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; Allocator = std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::parameters_type = geojson_linear<16ul, 4ul>; boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::indexable_getter = boost::geometry::index::indexable<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::value_equal = boost::geometry::index::equal_to<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >; boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::allocator_type = std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> >]'
include/mapnik/make_unique.hpp:36:65:   required from 'std::unique_ptr<T> std::make_unique(Args&& ...) [with T = boost::geometry::index::rtree<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, geojson_linear<16ul, 4ul> >; Args = {std::vector<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int>, std::allocator<std::pair<boost::geometry::model::box<boost::geometry::model::point<double, 2ul, boost::geometry::cs::cartesian> >, long unsigned int> > >&}]'
plugins/input/geojson/geojson_datasource.cpp:196:56:   required from 'void geojson_datasource::parse_geojson(const T&) [with T = std::basic_string<char>]'
plugins/input/geojson/geojson_datasource.cpp:123:37:   required from here
/usr/include/boost/geometry/index/rtree.hpp:1549:21: error: no type named 'type' in 'struct boost::geometry::index::detail::rtree::options_type<geojson_linear<16ul, 4ul> >'
             , root(0)
                     ^
/usr/include/boost/geometry/index/rtree.hpp:1549:21: error: using invalid field 'boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::members_holder::values_count'
/usr/include/boost/geometry/index/rtree.hpp:1549:21: error: using invalid field 'boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::members_holder::leafs_level'
/usr/include/boost/geometry/index/rtree.hpp:1549:21: error: using invalid field 'boost::geometry::index::rtree<Value, Options, IndexableGetter, EqualTo, Allocator>::members_holder::root'
scons: *** [plugins/input/geojson/geojson_datasource.os] Error 1
scons: building terminated because of errors.
Makefile:16: recipe for target 'mapnik' failed
make: *** [mapnik] Error 2
```

**Comment by ncopa** [comment]
This makes it compile at least:
```diff
--- ./plugins/input/geojson/geojson_datasource.hpp.orig
+++ ./plugins/input/geojson/geojson_datasource.hpp
@@ -73,7 +73,7 @@
                          choose_by_content_diff_tag,
                          split_default_tag,
                          linear_tag,
-                         node_s_mem_static_tag>;
+                         node_variant_static_tag>;
 };

 }}}}}
```

**Comment by artemp** [comment]
@ncopa - thanks for reporting! Looks like this has been fix upstream 

```c++
#if BOOST_VERSION >= 105700
                         node_variant_static_tag>;
#else
                         node_s_mem_static_tag>;

#endif
```

**Comment by springmeyer** [comment]
yes, this is fixed in master. We will be releasing current master as rc2 shortly: #2811. @ncopa if you could test rc2 once it is ready at #2811 that would be great.
