### ISSUE TITLE
mod_tile build with mapnik 3.0 error

### ISSUE THREAD

**Issue by creativeos** [mapnik/mapnik#2702]
hi,
I am trying to use the lastest version of mod_tile build with mapnik-3.0. When I complie mod_tile, I got the following error message. Should I build with mapnik2.x，if I want to use mod_tile. Or there is other method to fix it.

——————————————————————————————————————————————
'`src/gen_tile.cpp
src/gen_tile.cpp: In function ‘void parameterize_map_max_connections(mapnik::Map&, int)’:
src/gen_tile.cpp:180:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < m.layer_count(); i++) {
                                   ^
src/gen_tile.cpp: In function ‘protoCmd render(xmlmapconfig*, int, int, int, char*, metaTile&)’:
src/gen_tile.cpp:262:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (yy = 0; yy < render_size_ty; yy++) {
                       ^
src/gen_tile.cpp:263:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (xx = 0; xx < render_size_tx; xx++) {
                           ^
src/gen_tile.cpp:264:32: error: ‘image_data_32’ is not a member of ‘mapnik’
             mapnik::image_view<mapnik::image_data_32> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf.data());
                                ^
src/gen_tile.cpp:264:32: error: ‘image_data_32’ is not a member of ‘mapnik’
src/gen_tile.cpp:264:53: error: template argument 1 is invalid
             mapnik::image_view<mapnik::image_data_32> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf.data());
                                                     ^
src/gen_tile.cpp:264:57: error: invalid type in declaration before ‘(’ token
             mapnik::image_view<mapnik::image_data_32> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf.data());
                                                         ^
src/gen_tile.cpp:264:138: error: expression list treated as compound expression in initializer [-fpermissive]
             mapnik::image_view<mapnik::image_data_32> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf.data());
                                                                                                                                          ^
src/gen_tile.cpp:264:61: warning: left operand of comma operator has no effect [-Wunused-value]
             mapnik::image_view<mapnik::image_data_32> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf.data());
                                                             ^
src/gen_tile.cpp:264:81: warning: right operand of comma operator has no effect [-Wunused-value]
             mapnik::image_view<mapnik::image_data_32> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf.data());
                                                                                 ^
src/gen_tile.cpp:264:138: warning: right operand of comma operator has no effect [-Wunused-value]
             mapnik::image_view<mapnik::image_data_32> vw(xx * map->tilesize, yy * map->tilesize, map->tilesize, map->tilesize, buf.data());
                                                                                                                                          ^
src/gen_tile.cpp:264:138: warning: right operand of comma operator has no effect [-Wunused-value]
src/gen_tile.cpp:264:138: error: cannot convert ‘mapnik::image_data_rgba8 {aka mapnik::image_data<unsigned int>}’ to ‘int’ in initialization
make[1]: *** [src/renderd-gen_tile.o] Error 1

————————————————————————————————————————————————

**Comment by flippmoke** [comment]
@creativeos We have been making some changes to how images are dealt with internally within mapnik 3.x. It seems that mod_tile has not been updated yet for these changes. We are not quite done with all these changes, so a change to mod_tile might not be best quite yet. We are planning on doing a large release of changes that are currently in the release/image_data_any branch. Once this is released I can probably help with the changes in mod_tile.

**Comment by springmeyer** [comment]
@creativeos you can use https://github.com/springmeyer/mod_tile. I update it to work against Mapnik 3.x and it should work against Mapnik master.

**Comment by creativeos** [comment]
@springmeyer thank you for your help. But when I run "sudo make install", I got the following error message.  I have checked the libstdc++.so.6.
$ whereis libstdc++.so.6
libstdc++.so: /usr/lib/libstdc++.so.6 /usr/lib64/libstdc++.so.6
$ strings /usr/lib/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.3.2
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

$ strings /usr/lib64/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.3.2
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH


error message
---------------------------------------------------------------------------------------------
/usr/local/lib/libmapnik.so: undefined reference to `std::__detail::_Prime_rehash_policy::_M_need_rehash(unsigned long, unsigned long, unsigned long) const@GLIBCXX_3.4.18'
/usr/local/lib/libmapnik.so: undefined reference to `std::__detail::_List_node_base::_M_hook(std::__detail::_List_node_base*)@GLIBCXX_3.4.15'
/usr/local/lib/libmapnik.so: undefined reference to `std::__detail::_List_node_base::_M_unhook()@GLIBCXX_3.4.15'
/usr/local/lib/libmapnik.so: undefined reference to `std::out_of_range::~out_of_range()@GLIBCXX_3.4.15'
/usr/local/lib/libmapnik.so: undefined reference to `std::__detail::_Prime_rehash_policy::_M_next_bkt(unsigned long) const@GLIBCXX_3.4.18'
/usr/local/lib/libmapnik.so: undefined reference to `std::invalid_argument::~invalid_argument()@GLIBCXX_3.4.15'
/usr/local/lib/libmapnik.so: undefined reference to `std::__detail::_List_node_base::swap(std::__detail::_List_node_base&, std::__detail::_List_node_base&)@GLIBCXX_3.4.15'
/usr/local/lib/libmapnik.so: undefined reference to `std::_Hash_bytes(void const*, unsigned long, unsigned long)@CXXABI_1.3.5'
/usr/local/lib/libmapnik.so: undefined reference to `std::__detail::_List_node_base::_M_transfer(std::__detail::_List_node_base*, std::__detail::_List_node_base*)@GLIBCXX_3.4.15'
/usr/local/lib/libboost_regex.so: undefined reference to `std::overflow_error::~overflow_error()@GLIBCXX_3.4.15'
/usr/local/lib/libmapnik.so: undefined reference to `std::__throw_bad_function_call()@GLIBCXX_3.4.14'
collect2: ld returned 1 exit status
-------------------------------------------------------------------------------------------------------------------

**Comment by springmeyer** [comment]
> undefined reference to std::__detail::_Prime_rehash_policy::_M_need_rehash

This indicates you have a broken compiler toolchain - likely some mixed up or duplicate installs of g++/libstdc++. So, in short I don't think this has anything to do with mod_tile or mapnik. To solve it I recommend revisiting how you installed g++ and reflect on anything custom you might have done on your system to cause this.
