### ISSUE TITLE
Compilation issue "text/symbolizer_helpers.hpp:158:54: error: expected 'class' before 'GridAdapter'"

### ISSUE THREAD

**Issue by stoecker** [mapnik/mapnik#3881]
For openSUSE 42.3 mapnik fails to compile in version 3.0.19. Last version compiled there was 3.0.16 which worked fine.

It seems for upcoming openSUSE 15.0 it works again. Probably this line is using a VERY new C++ feature. If so please change code to not use the newest feature. It should at least compile with recent linux distributions (42.3 was released 2018-04-08, which is only a year ago).

Full compile log: https://build.opensuse.org/package/live_build_log/Application:Geo/mapnik/openSUSE_Leap_42.3/x86_64

**Comment by talaj** [comment]
Fixed in https://github.com/mapnik/mapnik/pull/3882.

**Comment by stoecker** [comment]
Thanks. I applied the patch and issue is solved.
