### ISSUE TITLE
Linker failure on master (4.0.0) with boost 1.71

### ISSUE THREAD

**Issue by bdon** [mapnik/mapnik#4167]
Hi, I would like to start hacking on custom Symbolizers and figured it would be better to work on `master` instead of a 3.0.x branch. Here's a linker error I'm running into when attempting a vanilla build with only core dependencies:

> /usr/bin/ld: src/libmapnik.so: undefined reference to `_ZN6mapnik7grammar10parse_ruleIN9__gnu_cxx17__normal_iteratorIPKcNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEN5boost6spirit2x37contextINS0_17rotate_node_classEKNSF_8sequenceINSI_INSF_17no_case_directiveINSF_14literal_stringIS5_NSE_13char_encoding8standardENSF_11unused_typeEEEEENSF_16expect_directiveINSF_12literal_charISM_SN_EEEEEENSQ_INSF_11alternativeINSF_6actionINSI_INSI_INSI_INSF_15rule_definitionINS0_8atom_tagENSW_INSF_11real_parserIdNSF_13real_policiesIdEEEENS0_3$_0EEEN6mapbox4util7variantIJNS_10value_nullEbldN6icu_6613UnicodeStringENS_9attributeENS_16global_attributeENS_23geometry_type_attributeENS16_17recursive_wrapperINS_10unary_nodeINS_4tags6negateEEEEENS1E_INS_11binary_nodeINS1G_4plusEEEEENS1E_INS1K_INS1G_5minusEEEEENS1E_INS1K_INS1G_4multEEEEENS1E_INS1K_INS1G_3divEEEEENS1E_INS1K_INS1G_3modEEEEENS1E_INS1K_INS1G_4lessEEEEENS1E_INS1K_INS1G_10less_equalEEEEENS1E_INS1K_INS1G_7greaterEEEEENS1E_INS1K_INS1G_13greater_equalEEEEENS1E_INS1K_INS1G_8equal_toEEEEENS1E_INS1K_INS1G_12not_equal_toEEEEENS1E_INS1F_INS1G_11logical_notEEEEENS1E_INS1K_INS1G_11logical_andEEEEENS1E_INS1K_INS1G_10logical_orEEEEENS1E_INS_16regex_match_nodeEEENS1E_INS_18regex_replace_nodeEEENS1E_INS_19unary_function_callEEENS1E_INS_20binary_function_callEEEEEELb0EEENSF_8optionalINSX_INS0_12sep_atom_tagENSI_INS31_ISS_EES14_EES2Z_Lb0EEEEEEES36_EESS_EENS0_3$_4EEENSW_INSI_INSI_INSI_INSF_4ruleINS0_8expr_tagES2Z_Lb0EEENSQ_INS31_INS3C_INS0_12sep_expr_tagES2Z_Lb0EEEEEEEEES3I_EEST_EES3A_EEEEEEEENSG_INS0_14transcoder_tagEKNS_10transcoderENSG_INSF_11skipper_tagEKNSF_10char_classINSL_5asciiENSF_9space_tagEEESN_EEEEEEEEbNS3C_INS0_16expression_classES2Z_Lb0EEERT_RKS45_RKT0_RS2Z_'

Steps to reproduce:
* Start an Ubuntu 20.04 vm (x86-64)
* sudo apt update && sudo apt install libboost-dev libz-dev libharfbuzz-dev libfreetype-dev libboost-system-dev libboost-filesystem-dev libboost-regex-dev make
* git clone https://github.com/mapnik/mapnik.git --recursive
* PYTHON=python3 ./configure
* PYTHON=python3 make

I encounter the same linker error on MacOS, also with boost version 1.71

**Comment by bdon** [comment]
I think I've solved this by moving to Boost 1.73 or 1.74 - not sure about 1.72. Hope this is helpful for others...
