### ISSUE TITLE
Build issue on Centos 7

### ISSUE THREAD

**Issue by paberline** [mapnik/mapnik#3468]
Hi,

I'm getting a build error:

`src/json/mapnik_json_geometry_grammar.cpp:27:31:   required from here
/usr/local/include/boost/spirit/home/qi/detail/alternative_function.hpp:30:46: error: no type named ‘types’ in ‘boost::spirit::qi::detail::find_substitute<boost::optional<boost::variant<int, mapnik::util::variant<mapnik::json::empty, mapnik::geometry::point<double>, std::vector<mapnik::geometry::point<double>, std::allocator<mapnik::geometry::point<double> > >`

Trying to build both 3.0.11 and master.

GCC v 5.4.0
Boost 1.61.0
Centos 7

Thanks
Peter

**Comment by paberline** [comment]
Hi

I was able to get a clean build using Boost 1.58.

Thanks
Peter

**Comment by artemp** [comment]
👍
