### ISSUE TITLE
visibility flags break builds with g++ 4.6.3 on Ubuntu 12.04

### ISSUE THREAD

**Issue by artemp** [mapnik/mapnik#1863]
# with -f-visibility-inline-hidden

``` c++
clang++ -o tests/cpp_tests/clipping_test-bin tests/cpp_tests/clipping_test.o -Ldeps/agg -Lsrc -L/usr/lib -L/usr/lib/x86_64-linux-gnu -lagg -lfreetype -lz -licuuc -lboost_filesystem -lboost_system -lboost_regex -lproj -lpng -ljpeg -ltiff -lxml2 -lboost_thread -lcairo -lmapnik -lsqlite3
tests/cpp_tests/clipping_test.o: In function `clip_line(mapnik::box2d<double> const&, mapnik::geometry<double, mapnik::vertex_vector>&)':
tests/cpp_tests/clipping_test.cpp:(.text+0x63): undefined reference to `mapnik::box2d<double>::minx() const'
tests/cpp_tests/clipping_test.cpp:(.text+0x73): undefined reference to `mapnik::box2d<double>::miny() const'
tests/cpp_tests/clipping_test.cpp:(.text+0x83): undefined reference to `mapnik::box2d<double>::maxx() const'
tests/cpp_tests/clipping_test.cpp:(.text+0x93): undefined reference to `mapnik::box2d<double>::maxy() const'
tests/cpp_tests/clipping_test.o: In function `main':
tests/cpp_tests/clipping_test.cpp:(.text+0xe4c): undefined reference to `mapnik::box2d<double>::from_string(std::string const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
