### ISSUE TITLE
Mapnik master (3.5.0) build failing on FreeBSD/PCBSD 10.2 with boost 1.60.0

### ISSUE THREAD

**Issue by PeterSprague** [mapnik/mapnik#3330]
Updating Mapnik for use with vector tiles.

gmake fails with error after successful ./configure.  Because ports only provides boost 1.55, I've built Boost 1.60, 1.59, & 1.58.  All produce differing link errors with Mapnik, then Mapnik build aborts.

Mapnik 3.4 did build with Boost 1.55 from ports.  3.5.0 doesn't seem to want to build with Boost 1.55 from ports.

Installed all dependencies.
boost in ports @ 1.55
```
cd /usr/local
wget https://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz/download
tar -xzvf download
rm download
cd boost_1_60_0
./bootstrap.sh --with-toolset=clang
./b2
```
successful

configure
`python scons/scons.py configure CXX=clang++ CC=clang ICU_LIB=/usr/local/lib ICU_INCLUDES=/usr/local/include HARFBUZZ_LIBS=/usr/local/lib HARFBUZZ_INCLUDES=/usr/local/include BOOST_INCLUDES=/usr/local/boost_1_60_0 BOOST_LIBS=/usr/local/boost_1_60_0/stage/lib`
tried with CXX=g++ CC=gcc5

`python scons/scons.py`
errors:
numerous boost warnings - "Use of this header (xxxxxxxx.hpp) is depreciated"

finishes with:
```
proj -ltiff -lwebp -lboost_system -lharfbuzz -ljpeg -licuuc -lfreetype -lz -lpthread
src/libmapnik.so: undefined reference to `boost::re_detail_106000::get_default_error_string(boost::regex_constants::error_type)'
src/libmapnik.so: undefined reference to `boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
src/libmapnik.so: undefined reference to `boost::re_detail_106000::get_mem_block()'
src/libmapnik.so: undefined reference to `boost::re_detail_106000::raise_runtime_error(std::runtime_error const&)'
src/libmapnik.so: undefined reference to `boost::re_detail_106000::put_mem_block(void*)'
src/libmapnik.so: undefined reference to `boost::re_detail_106000::verify_options(unsigned int, boost::regex_constants::_match_flags)'
src/libmapnik.so: undefined reference to `boost::re_detail_106000::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [demo/c++/rundemo] Error 1
scons: building terminated because of errors.
```
Not sure where to go from here.

**Comment by artemp** [comment]
@PeterSprague - you need to build `boost_regex` with ICU enabled
(http://www.boost.org/doc/libs/1_60_0/libs/regex/doc/html/boost_regex/install.html#boost_regex.install.building_with_unicode_and_icu_su)

**Comment by PeterSprague** [comment]
Will give it a go.  That was my next step, but shows as optional in configure.

**Comment by springmeyer** [comment]
I think this is not a "missing ICU support in regex" problem but something deeper. I also hit it in #3309 on OS X. Let's move over to tracking this at #3333.

**Comment by springmeyer** [comment]
@PeterSprague - take home is I would recommend using boost 1.59 for now until #3333 is fixed.

**Comment by PeterSprague** [comment]
Build Mapnik with Boost 1.59 successful
Build with Boost 1.60 also successful with revised workflow.

Revised workflow:
Install Boost 1.60
`cd /usr/local
wget https://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz/download
tar -xzvf download
rm download
cd boost_1_60_0
./bootstrap.sh --with-toolset=clang --with-icu --with-python=python --libdir=/usr/local/lib --includedir=/usr/local/include
./b2 toolset=clang install`

Build & install Mapnik:
`cd /usr/local
git clone https://github.com/mapnik/mapnik.git
cd mapnik
git checkout master
python scons/scons.py configure CXX=clang++ CC=clang ICU_LIB=/usr/local/lib ICU_INCLUDES=/usr/local/include HARFBUZZ_LIBS=/usr/local/lib HARFBUZZ_INCLUDES=/usr/local/include
python scons/scons.py
python scons/scons.py install`

Hopefully that helps.
