### ISSUE TITLE
Compile broken when Mapnik built single threaded

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#3096]
Building mapnik with `./configure THREADING=single` I'm seeing:

```
src/debug.cpp:56:27: error: redefinition of 'severity_env_check_' with a different type: 'std::atomic<bool>' vs 'bool'
std::atomic<bool> logger::severity_env_check_ {true};
                          ^
include/mapnik/debug.hpp:149:17: note: previous definition is here
    static bool severity_env_check_;
                ^
src/debug.cpp:57:27: error: redefinition of 'format_env_check_' with a different type: 'std::atomic<bool>' vs 'bool'
std::atomic<bool> logger::format_env_check_ {true};
                          ^
include/mapnik/debug.hpp:150:17: note: previous definition is here
    static bool format_env_check_;
                ^
src/debug.cpp:61:44: error: redefinition of 'severity_level_' with a different type: 'std::atomic<logger::severity_type>' vs 'mapnik::logger::severity_type'
std::atomic<logger::severity_type> logger::severity_level_ {
                                           ^
include/mapnik/debug.hpp:148:26: note: previous definition is here
    static severity_type severity_level_;
                         ^
3 errors generated.
```

**Comment by springmeyer** [comment]
broken since https://github.com/mapnik/mapnik/commit/a32fbdf635129530a9a1cc8a347a0cf4a8910ce3
