### ISSUE TITLE
mapnik v3.0.22 fails to build w/ boost v1.71.0

### ISSUE THREAD

**Issue by gen2** [mapnik/mapnik#4098]
Trying to build mapnik v3.0.22 with boost v1.71.0 failes:

```
x86_64-pc-linux-gnu-g++ -o src/json/mapnik_geometry_to_geojson.o -c -std=c++11 -DU_USING_ICU_NAMESPACE=0 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -Wshadow -O2 -pipe -fPIC -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -Ideps -Ideps/mapbox/variant/include -Ideps/agg/include -Iinclude -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 -I/usr/include/gdal -I/usr/include/postgresql-12 src/json/mapnik_geometry_to_geojson.cpp
In file included from /usr/include/boost/type_traits/is_convertible.hpp:20,
                 from /usr/include/boost/proto/matches.hpp:38,
                 from /usr/include/boost/phoenix/core/domain.hpp:12,
                 from /usr/include/boost/phoenix/core/actor.hpp:18,
                 from /usr/include/boost/phoenix/core.hpp:12,
                 from /usr/include/boost/spirit/include/phoenix_core.hpp:11,
                 from /usr/include/boost/spirit/home/support/terminal.hpp:17,
                 from /usr/include/boost/spirit/home/support/common_terminals.hpp:15,
                 from /usr/include/boost/spirit/home/karma/char/char.hpp:14,
                 from /usr/include/boost/spirit/home/karma/char.hpp:13,
                 from /usr/include/boost/spirit/home/karma.hpp:13,
                 from /usr/include/boost/spirit/include/karma.hpp:16,
                 from include/mapnik/json/geometry_generator_grammar.hpp:33,
                 from src/json/mapnik_geometry_to_geojson.cpp:25:
/usr/include/boost/spirit/home/support/attributes.hpp: In instantiation of 'struct boost::spirit::traits::transform_attribute<const mapnik::geometry::geometry<double>, const mapnik::geometry::geometry<double>&, boost::spirit::karma::domain, void>':
/usr/include/boost/spirit/home/karma/nonterminal/rule.hpp:293:42:   required from 'bool boost::spirit::karma::rule<OutputIterator, T1, T2, T3, T4>::generate(boost::spirit::karma::rule<OutputIterator, T1, T2, T3, T4>::output_iterator&, Context&, const Delimiter&, const Attribute&) const [with Context = boost::spirit::context<boost::fusion::cons<const mapnik::geometry::geometry<double>&, boost::fusion::nil_>, boost::spirit::locals<> >; Delimiter = boost::spirit::unused_type; Attribute = mapnik::geometry::geometry<double>; OutputIterator = std::back_insert_iterator<std::__cxx11::basic_string<char> >; T1 = const mapnik::geometry::geometry<double>&(); T2 = boost::spirit::unused_type; T3 = boost::spirit::unused_type; T4 = boost::spirit::unused_type; boost::spirit::karma::rule<OutputIterator, T1, T2, T3, T4>::output_iterator = boost::spirit::karma::detail::output_iterator<std::back_insert_iterator<std::__cxx11::basic_string<char> >, mpl_::int_<15>, boost::spirit::unused_type>]'
/usr/include/boost/spirit/home/karma/reference.hpp:46:65:   required from 'bool boost::spirit::karma::reference<Subject>::generate(OutputIterator&, Context&, const Delimiter&, const Attribute&) const [with OutputIterator = boost::spirit::karma::detail::output_iterator<std::back_insert_iterator<std::__cxx11::basic_string<char> >, mpl_::int_<15>, boost::spirit::unused_type>; Context = boost::spirit::context<boost::fusion::cons<const mapnik::geometry::geometry<double>&, boost::fusion::nil_>, boost::spirit::locals<> >; Delimiter = boost::spirit::unused_type; Attribute = mapnik::geometry::geometry<double>; Subject = const boost::spirit::karma::rule<std::back_insert_iterator<std::__cxx11::basic_string<char> >, const mapnik::geometry::geometry<double>&(), boost::spirit::unused_type, boost::spirit::unused_type, boost::spirit::unused_type>]'
/usr/include/boost/spirit/home/karma/generate.hpp:69:81:   required from 'bool boost::spirit::karma::generate(boost::spirit::karma::detail::output_iterator<OutputIterator, Derived>&, const Expr&, const Attr&) [with OutputIterator = std::back_insert_iterator<std::__cxx11::basic_string<char> >; Properties = mpl_::int_<15>; Expr = mapnik::json::geometry_generator_grammar<std::back_insert_iterator<std::__cxx11::basic_string<char> >, mapnik::geometry::geometry<double> >; Attr = mapnik::geometry::geometry<double>]'
/usr/include/boost/spirit/home/karma/generate.hpp:91:31:   required from 'bool boost::spirit::karma::generate(OutputIterator&, const Expr&, const Attr&) [with OutputIterator = std::back_insert_iterator<std::__cxx11::basic_string<char> >; Expr = mapnik::json::geometry_generator_grammar<std::back_insert_iterator<std::__cxx11::basic_string<char> >, mapnik::geometry::geometry<double> >; Attr = mapnik::geometry::geometry<double>]'
src/json/mapnik_geometry_to_geojson.cpp:34:62:   required from here
/usr/include/boost/spirit/home/support/attributes.hpp:963:9: error: static assertion failed: Transformed cannot be a reference type
         BOOST_STATIC_ASSERT_MSG(!is_reference<Transformed>::value,
         ^~~~~~~~~~~~~~~~~~~~~~~
```

boost is on version 1.71.0 (current stable on gentoo linux)

**Comment by am2222** [comment]
Any chance fix this bug with the latest boost version?

**Comment by tobwen** [comment]
Verified problem on Alpine Edge.

**Comment by gen2** [comment]
current master works w/ boost v-1.72.0 - but not w/ boost-v1.71.0 :-/

**Comment by am2222** [comment]
Boost Spirit 1.71 has a small bug which is fixed on 1.72

**Comment by gen2** [comment]
Will this be backported into the v3.0.x branch?

**Comment by tobwen** [comment]
For Alpine, I've backported v1.72 to stable. It works for Mapnik, but breaks other tools. So I have to wrap it into a container, I think.

**Comment by fxcoudert** [comment]
The fact that mapnik 3.0.22 does not build with Boost 1.72, and that no patch for  master was backported to the v3 branch, is blocking several important updates in Homebrew: https://github.com/Homebrew/homebrew-core/pull/48349 

Patches from master do not apply cleanly: https://github.com/mapnik/mapnik/pull/4094 and https://github.com/mapnik/mapnik/pull/4103/files
Applying the parts that do match to the 3.0.22 sources still results in a build error:

```
clang++ -o src/json/mapnik_geometry_to_geojson.o -c -std=c++11 -DU_USING_ICU_NAMESPACE=0 -stdlib=libc++ -fvisibility=hidden -fvisibility-inlines-hidden -Wall -ftemplate-depth-300 -Wsign-compare -Wshadow -Wno-unsequenced -Wtautological-compare -Wheader-hygiene -O3 -fPIC -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DHAVE_JPEG -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DDARWIN -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -Ideps -Ideps/mapbox/variant/include -Ideps/agg/include -Iinclude -I/usr/local/Cellar/gdal/2.4.2_4/include -I/usr/local/include -I/usr/local/opt/libtiff/include -I/usr/local/opt/webp/include -I/usr/local/opt/libpng/include -I/usr/local/opt/proj/include -I/usr/local/opt/jpeg/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/harfbuzz/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/boost/include -I/usr/include src/json/mapnik_geometry_to_geojson.cpp
In file included from src/json/mapnik_geometry_to_geojson.cpp:25:
In file included from include/mapnik/json/geometry_generator_grammar.hpp:33:
In file included from /usr/local/opt/boost/include/boost/spirit/include/karma.hpp:16:
In file included from /usr/local/opt/boost/include/boost/spirit/home/karma.hpp:13:
In file included from /usr/local/opt/boost/include/boost/spirit/home/karma/char.hpp:13:
In file included from /usr/local/opt/boost/include/boost/spirit/home/karma/char/char.hpp:23:
In file included from /usr/local/opt/boost/include/boost/spirit/home/karma/char/char_generator.hpp:17:
In file included from /usr/local/opt/boost/include/boost/spirit/home/karma/detail/extract_from.hpp:16:
In file included from /usr/local/opt/boost/include/boost/spirit/home/karma/detail/attributes.hpp:12:
/usr/local/opt/boost/include/boost/spirit/home/support/attributes.hpp:963:9: error: static_assert failed due to requirement
      '!is_reference<const mapnik::geometry::geometry<double> &>::value' "Transformed cannot be a reference type"
        BOOST_STATIC_ASSERT_MSG(!is_reference<Transformed>::value,
        ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/opt/boost/include/boost/static_assert.hpp:31:45: note: expanded from macro 'BOOST_STATIC_ASSERT_MSG'
#     define BOOST_STATIC_ASSERT_MSG( ... ) static_assert(__VA_ARGS__)
                                            ^             ~~~~~~~~~~~
/usr/local/opt/boost/include/boost/spirit/home/karma/nonterminal/rule.hpp:293:26: note: in instantiation of template class
      'boost::spirit::traits::transform_attribute<const mapnik::geometry::geometry<double>, const mapnik::geometry::geometry<double>
      &, boost::spirit::karma::domain, void>' requested here
                typename transform::type attr_ = transform::pre(attr);
                         ^
/usr/local/opt/boost/include/boost/spirit/home/karma/reference.hpp:46:30: note: in instantiation of function template specialization
      'boost::spirit::karma::rule<std::__1::back_insert_iterator<std::__1::basic_string<char> >, const
      mapnik::geometry::geometry<double> &(), boost::spirit::unused_type, boost::spirit::unused_type,
      boost::spirit::unused_type>::generate<boost::spirit::context<boost::fusion::cons<const mapnik::geometry::geometry<double> &,
      boost::fusion::nil_>, boost::spirit::locals<mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na,
      mpl_::na, mpl_::na> >, boost::spirit::unused_type, mapnik::geometry::geometry<double> >' requested here
            return ref.get().generate(sink, context, delim, attr);
                             ^
/usr/local/opt/boost/include/boost/spirit/home/karma/generate.hpp:69:45: note: in instantiation of function template specialization
      'boost::spirit::karma::reference<const boost::spirit::karma::rule<std::__1::back_insert_iterator<std::__1::basic_string<char>
      >, const mapnik::geometry::geometry<double> &(), boost::spirit::unused_type, boost::spirit::unused_type,
      boost::spirit::unused_type>
      >::generate<boost::spirit::karma::detail::output_iterator<std::__1::back_insert_iterator<std::__1::basic_string<char> >,
      mpl_::int_<15>, boost::spirit::unused_type>, boost::spirit::context<boost::fusion::cons<const
      mapnik::geometry::geometry<double> &, boost::fusion::nil_>, boost::spirit::locals<mpl_::na, mpl_::na, mpl_::na, mpl_::na,
      mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na, mpl_::na> >, boost::spirit::unused_type, mapnik::geometry::geometry<double>
      >' requested here
        return compile<karma::domain>(expr).generate(sink, context, unused, attr);
                                            ^
/usr/local/opt/boost/include/boost/spirit/home/karma/generate.hpp:91:23: note: in instantiation of function template specialization
      'boost::spirit::karma::generate<std::__1::back_insert_iterator<std::__1::basic_string<char> >, mpl_::int_<15>,
      mapnik::json::geometry_generator_grammar<std::__1::back_insert_iterator<std::__1::basic_string<char> >,
      mapnik::geometry::geometry<double> >, mapnik::geometry::geometry<double> >' requested here
        return karma::generate(sink, expr, attr);
                      ^
src/json/mapnik_geometry_to_geojson.cpp:34:34: note: in instantiation of function template specialization
      'boost::spirit::karma::generate<std::__1::back_insert_iterator<std::__1::basic_string<char> >,
      mapnik::json::geometry_generator_grammar<std::__1::back_insert_iterator<std::__1::basic_string<char> >,
      mapnik::geometry::geometry<double> >, mapnik::geometry::geometry<double> >' requested here
    return boost::spirit::karma::generate(sink, grammar, geom);
                                 ^
```

Unless the situation can be fixed and build restored, we will have to remove mapnik from Homebrew. It has failed to build for a significant amount of time now.

**Comment by tobwen** [comment]
@fxcoudert It _does_ build with 1.72 here (you need to check out mapnik from master branch), but it doesn't work wie 1.71.

**Comment by artemp** [comment]
@fxcoudert - I'll take a look tomorrow, cheers

**Comment by artemp** [comment]
f1cf712d50c14c06e815dd61cb71717068f1c795 - adds support for BOOST_1_72 (tested). This should also work with <= BOOST_1_71 (untested)
I'm planning to do quick `3.0.23` asap.
/cc @tobwen @gen2 @am2222 
@fxcoudert - could you verify all is good on macOS, I don't have access to this OS atm.

**Comment by am2222** [comment]
I think for the boost 1.71 the bug in the boost_sprite causes some errors. After fixing that bug I could build mapnik with no problem

**Comment by fxcoudert** [comment]
@artemp thanks for the fix. I am trying to build it: https://github.com/Homebrew/homebrew-core/pull/49355

**Comment by fxcoudert** [comment]
@artemp The fix is working on two macOS versions. I am seeing trouble with High Sierra, but it appears to be unrelated to this issue.

**Comment by artemp** [comment]
@fxcoudert - great :+1:

**Comment by giomasce** [comment]
Debian currently has Boost 1.71 and we might want to cherry pick the fix that version needs. Does anybody know the actual commit?

**Comment by artemp** [comment]
@giomasce : https://github.com/boostorg/spirit/pull/549/commits/10d027fd5cfd573471e80e2e3c2d0cb0616a6d65

**Comment by gen2** [comment]
@artemp:
> I'm planning to do a quick `3.0.23` asap.
is there any blocker we can help? I'm in urgent need for a working v3.0.x source on my new server ;)

**Comment by artemp** [comment]
@gen2 - no blockers. I'll try to find time this week, hopefully tomorrow.

**Comment by artemp** [comment]
@gen2 https://mapnik.org/news/release-3.0.23 
Closing.
