### ISSUE TITLE
mapnik 3.0.23 fails to build with boost 1.74.0

### ISSUE THREAD

**Issue by fxcoudert** [mapnik/mapnik#4196]
There appear to have been fixes to master in the meantime, could you please tag a new release?
Currently blocking Homebrew: https://github.com/Homebrew/homebrew-core/pull/65895

```
2020-11-29T17:06:00.7852790Z In file included from src/json/mapnik_json_generator_grammar.cpp:24:
2020-11-29T17:06:00.7853760Z In file included from include/mapnik/json/geometry_generator_grammar_impl.hpp:24:
2020-11-29T17:06:00.7854980Z In file included from include/mapnik/json/geometry_generator_grammar.hpp:32:
2020-11-29T17:06:00.7856020Z In file included from /usr/local/opt/boost/include/boost/spirit/include/karma.hpp:16:
2020-11-29T17:06:00.7857040Z In file included from /usr/local/opt/boost/include/boost/spirit/home/karma.hpp:17:
2020-11-29T17:06:00.7858080Z In file included from /usr/local/opt/boost/include/boost/spirit/home/karma/nonterminal.hpp:13:
2020-11-29T17:06:00.7862480Z /usr/local/opt/boost/include/boost/spirit/home/karma/nonterminal/rule.hpp:140:9: error: static_assert failed due to requirement '!is_reference<const mapnik::feature_impl &>::value' "Const/reference qualifiers on Karma rule attribute are meaningless"
2020-11-29T17:06:00.7864040Z         BOOST_STATIC_ASSERT_MSG(
2020-11-29T17:06:00.7864490Z         ^
2020-11-29T17:06:00.7865980Z /usr/local/opt/boost/include/boost/static_assert.hpp:31:45: note: expanded from macro 'BOOST_STATIC_ASSERT_MSG'
2020-11-29T17:06:00.7867040Z #     define BOOST_STATIC_ASSERT_MSG( ... ) static_assert(__VA_ARGS__)
2020-11-29T17:06:00.7867640Z                                             ^             ~~~~~~~~~~~
2020-11-29T17:06:00.7870650Z /usr/local/opt/boost/include/boost/spirit/home/karma/nonterminal/grammar.hpp:43:26: note: in instantiation of template class 'boost::spirit::karma::rule<std::__1::back_insert_iterator<std::__1::basic_string<char> >, const mapnik::feature_impl &(), boost::spirit::unused_type, boost::spirit::unused_type, boost::spirit::unused_type>' requested here
2020-11-29T17:06:00.7872610Z         typedef typename start_type::properties properties;
2020-11-29T17:06:00.7873240Z                          ^
2020-11-29T17:06:00.7876640Z include/mapnik/json/properties_generator_grammar.hpp:63:39: note: in instantiation of template class 'boost::spirit::karma::grammar<std::__1::back_insert_iterator<std::__1::basic_string<char> >, const mapnik::feature_impl &(), boost::spirit::unused_type, boost::spirit::unused_type, boost::spirit::unused_type>' requested here
2020-11-29T17:06:00.7878760Z struct properties_generator_grammar : karma::grammar<OutputIterator, KeyValueStore const&()>
2020-11-29T17:06:00.7879640Z                                       ^
2020-11-29T17:06:00.7882050Z src/json/mapnik_json_generator_grammar.cpp:32:31: note: in instantiation of template class 'mapnik::json::properties_generator_grammar<std::__1::back_insert_iterator<std::__1::basic_string<char> >, mapnik::feature_impl>' requested here
2020-11-29T17:06:00.7883790Z template struct mapnik::json::properties_generator_grammar<sink_type, mapnik::feature_impl>;
2020-11-29T17:06:00.7885310Z                               ^
2020-11-29T17:06:00.7886010Z In file included from src/json/mapnik_json_generator_grammar.cpp:24:
2020-11-29T17:06:00.7886980Z In file included from include/mapnik/json/geometry_generator_grammar_impl.hpp:24:
2020-11-29T17:06:00.7888050Z In file included from include/mapnik/json/geometry_generator_grammar.hpp:32:
2020-11-29T17:06:00.7889050Z In file included from /usr/local/opt/boost/include/boost/spirit/include/karma.hpp:16:
2020-11-29T17:06:00.7890060Z In file included from /usr/local/opt/boost/include/boost/spirit/home/karma.hpp:17:
2020-11-29T17:06:00.7891100Z In file included from /usr/local/opt/boost/include/boost/spirit/home/karma/nonterminal.hpp:14:
2020-11-29T17:06:00.7894320Z /usr/local/opt/boost/include/boost/spirit/home/karma/nonterminal/grammar.hpp:52:55: error: no member named 'params_size' in 'boost::spirit::karma::rule<std::__1::back_insert_iterator<std::__1::basic_string<char> >, const mapnik::feature_impl &(), boost::spirit::unused_type, boost::spirit::unused_type, boost::spirit::unused_type>'
2020-11-29T17:06:00.7896280Z         static size_t const params_size = start_type::params_size;
2020-11-29T17:06:00.7897080Z                                           ~~~~~~~~~~~~^
2020-11-29T17:06:00.7899900Z include/mapnik/json/properties_generator_grammar.hpp:63:39: note: in instantiation of template class 'boost::spirit::karma::grammar<std::__1::back_insert_iterator<std::__1::basic_string<char> >, const mapnik::feature_impl &(), boost::spirit::unused_type, boost::spirit::unused_type, boost::spirit::unused_type>' requested here
2020-11-29T17:06:00.7902020Z struct properties_generator_grammar : karma::grammar<OutputIterator, KeyValueStore const&()>
2020-11-29T17:06:00.7902840Z                                       ^
2020-11-29T17:06:00.7905400Z src/json/mapnik_json_generator_grammar.cpp:32:31: note: in instantiation of template class 'mapnik::json::properties_generator_grammar<std::__1::back_insert_iterator<std::__1::basic_string<char> >, mapnik::feature_impl>' requested here
2020-11-29T17:06:00.7907140Z template struct mapnik::json::properties_generator_grammar<sink_type, mapnik::feature_impl>;
2020-11-29T17:06:00.7907900Z                               ^
2020-11-29T17:06:00.7908350Z 2 errors generated.
2020-11-29T17:06:00.7909030Z scons: *** [src/json/mapnik_json_generator_grammar.o] Error 1
2020-11-29T17:06:00.7909780Z scons: building terminated because of errors.
2020-11-29T17:06:00.7911080Z make: *** [src/json/libmapnik-json.a] Error 2
```

**Comment by artemp** [comment]
@fxcoudert - Did you mean `3.0.23`? I'll take a look, it might not be straight forward to port. I think better approach would be to finaly release mapnik-v4.x.x (aka master).

**Comment by fxcoudert** [comment]
Yes sorry, 3.0.23

**Comment by redneb** [comment]
I was able to get mapnik 3.0.23 compile against boost 1.74 using [this patch](https://github.com/redneb/gentoo-mapnik-overlay/blob/master/sci-geosciences/mapnik/files/mapnik-3.0.23-boost-1.74.patch). It is essentially ed1696db4ab78cf7437688951adbe625f66e5358 backported from master, with the addition of a couple of missing `#include`s. I've only tested this under linux.

**Comment by iMichka** [comment]
When is the next mapnik release planned? The patch is quite huge. We could use it in homebrew, but I would prefer a new release.

**Comment by artemp** [comment]
Ok, patch looks good, thanks @redneb.  I'm aiming to release `3.0.24` before the end of this year. 
/cc @fxcoudert @iMichka

**Comment by artemp** [comment]
https://github.com/mapnik/mapnik/commit/6f0bab62463cc0e38707c0ae677d5e50c556052b

**Comment by chenrui333** [comment]
> Ok, patch looks good, thanks @redneb. I'm aiming to release `3.0.24` before the end of this year.
> /cc @fxcoudert @iMichka

Do we still have 3.0.24 in plan? Looks like it failed to build against boost 1.75.0 now. 


<details>
<summary>build error</summary>

```
clang++ -o src/renderer_common/render_group_symbolizer.os -c -std=c++11 -DU_USING_ICU_NAMESPACE=0 -stdlib=libc++ -fvisibility=hidden -fvisibility-inlines-hidden -Wall -ftemplate-depth-300 -Wsign-compare -Wshadow -Wno-unsequenced -Wtautological-compare -Wheader-hygiene -O3 -fPIC -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DDARWIN -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -Ideps -Ideps/mapbox/variant/include -Ideps/agg/include -Iinclude -I/usr/local/Cellar/gdal/3.2.0_3/include -I/usr/local/include -I/usr/local/opt/libtiff/include -I/usr/local/opt/webp/include -I/usr/local/opt/libpng/include -I/usr/local/opt/proj/include -I/usr/local/opt/jpeg/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/harfbuzz/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/boost/include -I/usr/include -I/usr/local/Cellar/libffi/3.3/include -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/glib/2.66.4/include -I/usr/local/Cellar/glib/2.66.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.66.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pixman/0.40.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.16.0_4/include/cairo src/renderer_common/render_group_symbolizer.cpp
clang++ -o src/renderer_common/render_markers_symbolizer.os -c -std=c++11 -DU_USING_ICU_NAMESPACE=0 -stdlib=libc++ -fvisibility=hidden -fvisibility-inlines-hidden -Wall -ftemplate-depth-300 -Wsign-compare -Wshadow -Wno-unsequenced -Wtautological-compare -Wheader-hygiene -O3 -fPIC -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DDARWIN -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -Ideps -Ideps/mapbox/variant/include -Ideps/agg/include -Iinclude -I/usr/local/Cellar/gdal/3.2.0_3/include -I/usr/local/include -I/usr/local/opt/libtiff/include -I/usr/local/opt/webp/include -I/usr/local/opt/libpng/include -I/usr/local/opt/proj/include -I/usr/local/opt/jpeg/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/harfbuzz/include -I/usr/local/opt/icu4c/include -I/usr/local/opt/boost/include -I/usr/include -I/usr/local/Cellar/libffi/3.3/include -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -I/usr/local/Cellar/fontconfig/2.13.1/include -I/usr/local/Cellar/pcre/8.44/include -I/usr/local/Cellar/glib/2.66.4/include -I/usr/local/Cellar/glib/2.66.4/include/glib-2.0 -I/usr/local/Cellar/glib/2.66.4/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pixman/0.40.0/include/pixman-1 -I/usr/local/Cellar/cairo/1.16.0_4/include/cairo src/renderer_common/render_markers_symbolizer.cpp
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:54:12: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    : std::conditional_t<Trait::value, conjunction<Traits...>, Trait>
      ~~~~~^~~~~~~~~~~~~
           conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:68:12: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    : std::conditional_t<Trait::value, Trait, disjunction<Traits...>>
      ~~~~~^~~~~~~~~~~~~
           conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:95:18: error: no template named 'remove_cv_t' in namespace 'std'; did you mean simply 'remove_cv_t'?
    using type = std::remove_cv_t<std::remove_reference_t<T>>;
                 ^~~~~~~~~~~~~~~~
                 remove_cv_t
/usr/local/opt/boost/include/boost/type_traits/remove_cv.hpp:39:23: note: 'remove_cv_t' declared here
   template <class T> using remove_cv_t = typename remove_cv<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:95:35: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
    using type = std::remove_cv_t<std::remove_reference_t<T>>;
                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                  remove_reference_t
/usr/local/opt/boost/include/boost/type_traits/remove_reference.hpp:53:23: note: 'remove_reference_t' declared here
   template <class T> using remove_reference_t = typename remove_reference<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:105:18: error: no template named 'remove_const_t' in namespace 'std'; did you mean simply 'remove_const_t'?
    using type = std::remove_const_t<std::remove_reference_t<T>>;
                 ^~~~~~~~~~~~~~~~~~~
                 remove_const_t
/usr/local/opt/boost/include/boost/type_traits/remove_const.hpp:33:23: note: 'remove_const_t' declared here
   template <class T> using remove_const_t = typename remove_const<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:105:38: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
    using type = std::remove_const_t<std::remove_reference_t<T>>;
                                     ^~~~~~~~~~~~~~~~~~~~~~~
                                     remove_reference_t
/usr/local/opt/boost/include/boost/type_traits/remove_reference.hpp:53:23: note: 'remove_reference_t' declared here
   template <class T> using remove_reference_t = typename remove_reference<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:115:18: error: no template named 'remove_const_t' in namespace 'std'; did you mean simply 'remove_const_t'?
    using type = std::remove_const_t
                 ^~~~~~~~~~~~~~~~~~~
                 remove_const_t
/usr/local/opt/boost/include/boost/type_traits/remove_const.hpp:33:23: note: 'remove_const_t' declared here
   template <class T> using remove_const_t = typename remove_const<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:117:13: error: no template named 'remove_pointer_t' in namespace 'std'; did you mean simply 'remove_pointer_t'?
            std::remove_pointer_t<std::remove_reference_t<T>>
            ^~~~~~~~~~~~~~~~~~~~~
            remove_pointer_t
/usr/local/opt/boost/include/boost/type_traits/remove_pointer.hpp:78:23: note: 'remove_pointer_t' declared here
   template <class T> using remove_pointer_t = typename remove_pointer<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:117:35: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
            std::remove_pointer_t<std::remove_reference_t<T>>
                                  ^~~~~~~~~~~~~~~~~~~~~~~
                                  remove_reference_t
/usr/local/opt/boost/include/boost/type_traits/remove_reference.hpp:53:23: note: 'remove_reference_t' declared here
   template <class T> using remove_reference_t = typename remove_reference<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:129:23: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    using type = std::conditional_t
                 ~~~~~^~~~~~~~~~~~~
                      conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:131:39: error: no template named 'remove_reference_t' in namespace 'std'; did you mean simply 'remove_reference_t'?
                        std::is_const<std::remove_reference_t<From>>::value,
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      remove_reference_t
/usr/local/opt/boost/include/boost/type_traits/remove_reference.hpp:53:23: note: 'remove_reference_t' declared here
   template <class T> using remove_reference_t = typename remove_reference<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:132:25: error: no template named 'add_const_t' in namespace 'std'; did you mean simply 'add_const_t'?
                        std::add_const_t<To>,
                        ^~~~~~~~~~~~~~~~
                        add_const_t
/usr/local/opt/boost/include/boost/type_traits/add_const.hpp:46:23: note: 'add_const_t' declared here
   template <class T> using add_const_t = typename add_const<T>::type;
                      ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:32:
In file included from /usr/local/opt/boost/include/boost/geometry/geometries/register/linestring.hpp:19:
In file included from /usr/local/opt/boost/include/boost/geometry/core/tag.hpp:23:
/usr/local/opt/boost/include/boost/geometry/util/type_traits_std.hpp:166:18: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    typedef std::conditional_t
            ~~~~~^~~~~~~~~~~~~
                 conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/local/opt/boost/include/boost/geometry.hpp:17:
In file included from /usr/local/opt/boost/include/boost/geometry/geometry.hpp:34:
In file included from /usr/local/opt/boost/include/boost/geometry/core/closure.hpp:24:
/usr/local/opt/boost/include/boost/geometry/core/ring_type.hpp:96:18: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
    typedef std::conditional_t
            ~~~~~^~~~~~~~~~~~~
                 conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/local/opt/boost/include/boost/geometry.hpp:17:
In file included from /usr/local/opt/boost/include/boost/geometry/geometry.hpp:34:
In file included from /usr/local/opt/boost/include/boost/geometry/core/closure.hpp:24:
/usr/local/opt/boost/include/boost/geometry/core/ring_type.hpp:111:18: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
            std::conditional_t
            ~~~~~^~~~~~~~~~~~~
                 conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/local/opt/boost/include/boost/geometry.hpp:17:
In file included from /usr/local/opt/boost/include/boost/geometry/geometry.hpp:34:
In file included from /usr/local/opt/boost/include/boost/geometry/core/closure.hpp:24:
/usr/local/opt/boost/include/boost/geometry/core/ring_type.hpp:127:18: error: no template named 'conditional_t' in namespace 'std'; did you mean 'conditional'?
            std::conditional_t
            ~~~~~^~~~~~~~~~~~~
                 conditional
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:429:33: note: 'conditional' declared here
    struct _LIBCPP_TEMPLATE_VIS conditional {typedef _If type;};
                                ^
In file included from src/renderer_common/render_markers_symbolizer.cpp:27:
In file included from include/mapnik/marker_helpers.hpp:29:
In file included from include/mapnik/geometry_centroid.hpp:27:
In file included from include/mapnik/geometry_adapters.hpp:38:
In file included from /usr/local/opt/boost/include/boost/geometry.hpp:17:
In file included from /usr/local/opt/boost/include/boost/geometry/geometry.hpp:35:
/usr/local/opt/boost/include/boost/geometry/core/coordinate_dimension.hpp:101:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension()
                      ^
/usr/local/opt/boost/include/boost/geometry/core/coordinate_dimension.hpp:111:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension_less_equal()
                      ^
/usr/local/opt/boost/include/boost/geometry/core/coordinate_dimension.hpp:117:23: error: constexpr function's return type 'void' is not a literal type
constexpr inline void assert_dimension_greater_equal()
                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
scons: *** [src/renderer_common/render_markers_symbolizer.os] Error 1
scons: building terminated because of errors.
make: *** [src/json/libmapnik-json.a] Error 2

```

</details>

**Comment by artemp** [comment]
### Mapnik v3.0.24 release
This release adds support for `BOOST_VERSION >= 1.74.0`  
 
* https://mapnik.org/news/release-3.0.24
* https://github.com/mapnik/mapnik/blob/v3.0.24/CHANGELOG.md#3024 
/cc @redneb @fxcoudert @iMichka @chenrui333 
Thanks!

**Comment by iMichka** [comment]
Thanks !

**Comment by artemp** [comment]
> > Ok, patch looks good, thanks @redneb. I'm aiming to release `3.0.24` before the end of this year.
> > /cc @fxcoudert @iMichka
> 
> Do we still have 3.0.24 in plan? Looks like it failed to build against boost 1.75.0 now.

Thanks for reporting, yes, I can replicate ^^ It looks like Boost.Geometry requires c++17 support in 1.75. I'll need to verify if this is intentional or just a oversight. In any case, I'm planning to stop supporting `v3.0.x` and instead focus on `v4.x.x (current master)`

**Comment by chenrui333** [comment]
> > > Ok, patch looks good, thanks @redneb. I'm aiming to release `3.0.24` before the end of this year.
> > > /cc @fxcoudert @iMichka
> > 
> > 
> > Do we still have 3.0.24 in plan? Looks like it failed to build against boost 1.75.0 now.
> 
> Thanks for reporting, yes, I can replicate ^^ It looks like Boost.Geometry requires c++17 support in 1.75. I'll need to verify if this is intentional or just a oversight. In any case, I'm planning to stop supporting `v3.0.x` and instead focus on `v4.x.x (current master support boost 1.75)` @chenrui333

got you, thanks!

**Comment by fxcoudert** [comment]
Opened a new issue: https://github.com/mapnik/mapnik/issues/4201
