### ISSUE TITLE
Windows build errors

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#2734]
This likely broke on windows in #2731

@flippmoke - just noticing this. This may block us on tagging node-mapnik tomorrow unless I can figure out whats going on when I awake.

```
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(495): error C2678: binary '==': no operator found which take
 s a left-hand operand of type 'const mapnik::image_rgba8' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\process_
 line_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(495): error C2678: binary '==': no operator found which take
 s a left-hand operand of type 'const mapnik::image_gray8' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\process_
 line_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(504): error C2678: binary '<': no operator found which takes
  a left-hand operand of type 'const mapnik::image_gray8' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\process_l
 ine_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(504): error C2678: binary '<': no operator found which takes
  a left-hand operand of type 'const mapnik::image_gray8s' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\process_
 line_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(495): error C2678: binary '==': no operator found which take
 s a left-hand operand of type 'const mapnik::image_gray8s' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\process
 _line_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(495): error C2678: binary '==': no operator found which take
 s a left-hand operand of type 'const mapnik::image_gray16' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\process
 _line_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(504): error C2678: binary '<': no operator found which takes
  a left-hand operand of type 'const mapnik::image_gray16' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\process_
 line_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(504): error C2678: binary '<': no operator found which takes
  a left-hand operand of type 'const mapnik::image_gray16s' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\process
 _line_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(495): error C2678: binary '==': no operator found which take
 s a left-hand operand of type 'const mapnik::image_gray16s' (or there is no acceptable conversion) (compiling source file ..\..\src\agg\proces
 s_line_pattern_symbolizer.cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
   c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(495): error C2678: binary '==': no operator found which take
```

**Comment by springmeyer** [comment]
```
   29>c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(504): error C2676: binary '<': 'const mapnik::image_gray64f' d
      oes not define this operator or a conversion to a type acceptable to the predefined operator (compiling source file ..\..\src\agg\agg_renderer
      .cpp) [c:\code\mapnik-deps-64-2\packages\mapnik-master\mapnik-gyp\build\mapnik.vcxproj]
        c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(520): note: see reference to function template instantiation
         'bool mapnik::util::detail::less_comp::operator ()<T>(const T &,const T &) const' being compiled
                with
                [
                    T=mapnik::image_gray64f
                ] (compiling source file ..\..\src\agg\agg_renderer.cpp)
        c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(291): note: see reference to function template instantiation
         'bool mapnik::util::detail::comparer<mapnik::util::variant<mapnik::image_null,mapnik::image_rgba8,mapnik::image_gray8,mapnik::image_gray8s,
        mapnik::image_gray16,mapnik::image_gray16s,mapnik::image_gray32,mapnik::image_gray32s,mapnik::image_gray32f,mapnik::image_gray64,mapnik::ima
        ge_gray64s,mapnik::image_gray64f>,mapnik::util::detail::less_comp>::operator ()<T>(const T &) const' being compiled
                with
                [
                    T=mapnik::image_gray64f
                ] (compiling source file ..\..\src\agg\agg_renderer.cpp)
        c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(291): note: see reference to function template instantiation
         'bool mapnik::util::detail::comparer<mapnik::util::variant<mapnik::image_null,mapnik::image_rgba8,mapnik::image_gray8,mapnik::image_gray8s,
        mapnik::image_gray16,mapnik::image_gray16s,mapnik::image_gray32,mapnik::image_gray32s,mapnik::image_gray32f,mapnik::image_gray64,mapnik::ima
        ge_gray64s,mapnik::image_gray64f>,mapnik::util::detail::less_comp>::operator ()<T>(const T &) const' being compiled
                with
                [
                    T=mapnik::image_gray64f
                ] (compiling source file ..\..\src\agg\agg_renderer.cpp)
        c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(288): note: while compiling class template member function '
        bool mapnik::util::detail::dispatcher<F,V,R,mapnik::image_gray64f>::apply_const(const V &,F)'
                with
                [
                    F=mapnik::util::detail::comparer<mapnik::util::variant<mapnik::image_null,mapnik::image_rgba8,mapnik::image_gray8,mapnik::image_
        gray8s,mapnik::image_gray16,mapnik::image_gray16s,mapnik::image_gray32,mapnik::image_gray32s,mapnik::image_gray32f,mapnik::image_gray64,mapn
        ik::image_gray64s,mapnik::image_gray64f>,mapnik::util::detail::less_comp>
        ,            V=mapnik::util::variant<mapnik::image_null,mapnik::image_rgba8,mapnik::image_gray8,mapnik::image_gray8s,mapnik::image_gray16,ma
        pnik::image_gray16s,mapnik::image_gray32,mapnik::image_gray32s,mapnik::image_gray32f,mapnik::image_gray64,mapnik::image_gray64s,mapnik::imag
        e_gray64f>
        ,            R=bool
                ] (compiling source file ..\..\src\agg\agg_renderer.cpp)
        c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(295): note: see reference to function template instantiation
         'bool mapnik::util::detail::dispatcher<F,V,R,mapnik::image_gray64f>::apply_const(const V &,F)' being compiled
                with
                [
                    F=mapnik::util::detail::comparer<mapnik::util::variant<mapnik::image_null,mapnik::image_rgba8,mapnik::image_gray8,mapnik::image_
        gray8s,mapnik::image_gray16,mapnik::image_gray16s,mapnik::image_gray32,mapnik::image_gray32s,mapnik::image_gray32f,mapnik::image_gray64,mapn
        ik::image_gray64s,mapnik::image_gray64f>,mapnik::util::detail::less_comp>
        ,            V=mapnik::util::variant<mapnik::image_null,mapnik::image_rgba8,mapnik::image_gray8,mapnik::image_gray8s,mapnik::image_gray16,ma
        pnik::image_gray16s,mapnik::image_gray32,mapnik::image_gray32s,mapnik::image_gray32f,mapnik::image_gray64,mapnik::image_gray64s,mapnik::imag
        e_gray64f>
        ,            R=bool
                ] (compiling source file ..\..\src\agg\agg_renderer.cpp)
        c:\code\mapnik-deps-64-2\packages\mapnik-master\include\mapnik/util/variant.hpp(295): note: see reference to class template instantiation 'm
        apnik::util::detail::dispatcher<F,V,R,mapnik::image_gray64f>' being compiled
                with
                [
                    F=mapnik::util::detail::comparer<mapnik::util::variant<mapnik::image_null,mapnik::image_rgba8,mapnik::image_gray8,mapnik::image_
        gray8s,mapnik::image_gray16,mapnik::image_gray16s,mapnik::image_gray32,mapnik::image_gray32s,mapnik::image_gray32f,mapnik::image_gray64,mapn
        ik::image_gray64s,mapnik::image_gray64f>,mapnik::util::detail::less_comp>
        ,            V=mapnik::util::variant<mapnik::image_null,mapnik::image_rgba8,mapnik::image_gray8,mapnik::image_gray8s,mapnik::image_gray16,ma
        pnik::image_gray16s,mapnik::image_gray32,mapnik::image_gray32s,mapnik::image_gray32f,mapnik::image_gray64,mapnik::image_gray64s,mapnik::imag
        e_gray64f>
        ,            R=bool
                ] (compiling source file ..\..\src\agg\agg_renderer.cpp)
```

**Comment by BergWerkGIS** [comment]
Just a reminder how get automated windows builds:

* commit with `[publish binary]` to https://github.com/mapbox/windows-builds
* goto to https://travis-ci.org/mapbox/windows-builds
* locate the URL of the build server. Should be available __~30 seconds__ after the travis build has started
![image](https://cloud.githubusercontent.com/assets/4549888/6736140/492e68b2-ce63-11e4-8f2a-d1c151470596.png)
* __wait about 10 minutes__ for our build server to boot and start its work
* paste the URL into your browser to monitor the progress in real time
* don't refresh the page after you haven't looked at it for a longer time, the server powers down as soon as the build is finished. So the webpage is gone as soon as the build server is gone.
* whole thing takes __~1hr all in all__
* binaries (if succesful) are here: s3://mapnik/dist/dev/
* log files (always): s3://mapnik/dist/dev/windows-build-server-logs/

**Comment by springmeyer** [comment]
@BergWerkGIS - thank you. I wonder if we should hook up to mapnik core repo to make it even easier to catch when we introduce build errors? Something like `[test win] would trigger a build`?

**Comment by BergWerkGIS** [comment]
@springmeyer sure, that's the plan.
I just didn't want to pollute the mapnik commit history with endless `--allow-empty` commits, during figuring out the AWS/EC2 stuff.
If you could spare a minute tomorrow or Monday we can talk details.

**Comment by flippmoke** [comment]
So covering what I learned in solving this problem:

Currently the shift to using an implementation header presented some problems in our system with using variants. It seems that in VC++ it is demanding that all the inline function in the `variant` [base class](https://github.com/mapnik/mapnik/blob/master/include/mapnik/util/variant.hpp#L532) be able to be implemented even if they are not used. The solution was to add several more operators and a default construtor for some of the image classes. 

I noticed that the default constructor is only important because the [default constructor for variant](https://github.com/mapnik/mapnik/blob/master/include/mapnik/util/variant.hpp#L551-L555) will require a default constructor for the first item in `util::variant<item1,item2,item3>`. In this case item1 would need a default constructor for that variant to be happy in VC++. 

This was not an issue in our changes to the `image_any` variant because we have `image_null` first and it that has a default constructor. However, `image_view_any` variant didn't have any variants with a default constructor so I added a `image_view_null` as a solution, putting it as the first item in the variant list.
