### ISSUE TITLE
mapnik.render_layer error

### ISSUE THREAD

**Issue by rostom** [mapnik/mapnik#1200]
Newbie with Mapnik (and Python)...

I'm working with mapnik (2.0.1rc0), tilestache, openlayers, and werkzeug under Windows XP and Python (2.7.2) .  My map tiles are being generated fine, but I'm getting errors in the tilestache server when it tries to process json requests using utfgrid and openlayers. Below is the last line of the exception stack:

<b>  File "C:\Python27\lib\site-packages\TileStache\Goodies\Providers\MapnikGrid.py", line 84, in renderTile
    mapnik.render_layer(self.mapnik, grid, layer=self.layer_index, fields=self.fields)
AttributeError: 'module' object has no attribute 'render_layer'</b>

I am posting this in the mapnik arena because it appears that the error is in regards to mapnik missing 'render_layer'.  Does the Windows version of mapnik that I'm using not support this?

Any ideas or help would be appreciated.  Thanks in advance.
