### ISSUE TITLE
function_eval.hpp:116:13: error: wrong number of template arguments (3, should be 2)

### ISSUE THREAD

**Issue by strk** [mapnik/mapnik#2443]
Build started to fail in the 2.2.x branch due to some recent commit.
The error message:

```
include/mapnik/expression_grammar_impl.hpp:121:24:   required from ‘mapnik::expression_grammar<Iterator>::expression_grammar(const mapnik::transcod
er&) [with Iterator = __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >]’
src/expression_grammar.cpp:32:25:   required from here
/usr/include/boost/spirit/home/phoenix/core/detail/function_eval.hpp:116:13: error: wrong number of template arguments (3, should be 2)
             function_apply;
             ^
```

I have boost 1.54 installed. Might have been broken by 08f651289dcb6f5ab9f0be137190c19e2fbc045a (adding support for boost 1.56 as per #2368).

The commit before that one build fine
