### ISSUE TITLE
vertex converters will not compile with boost 1.47

### ISSUE THREAD

**Issue by springmeyer** [mapnik/mapnik#1885]
We promise boost >= 1.47 support in `INSTALL.md` but currently (seen on clang++ and OS X) the compile fails:

```
In file included from src/agg/process_line_symbolizer.cpp:24:
In file included from include/mapnik/feature.hpp:29:
In file included from include/mapnik/value.hpp:36:
In file included from /opt/boost-47/include/boost/variant/variant.hpp:31:
In file included from /opt/boost-47/include/boost/variant/detail/initializer.hpp:27:
In file included from /opt/boost-47/include/boost/mpl/iter_fold.hpp:18:
/opt/boost-47/include/boost/mpl/begin_end.hpp:34:22: error: incomplete type 'boost::mpl::begin_impl<boost::fusion::fusion_sequence_tag>' named in
      nested name specifier
    typedef typename begin_impl< tag_ >
                     ^~~~~~~~~~~~~~~~~~
/opt/boost-47/include/boost/mpl/aux_/at_impl.hpp:33:24: note: in instantiation of template class 'boost::mpl::begin<boost::fusion::vector<const
      mapnik::box2d<double> &,
      agg::rasterizer_outline_aa<agg::renderer_outline_aa<agg::renderer_base<agg::pixfmt_custom_blend_rgba<agg::comp_op_adaptor_rgba_pre<agg::rgba8,
      agg::order_rgba>, agg::row_ptr_cache<unsigned char> > > >, agg::line_coord> &, const mapnik::line_symbolizer &, const mapnik::CoordTransform
      &, const mapnik::proj_transform &, const agg::trans_affine &, double, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_> >'
      requested here
              typename begin<Sequence>::type
                       ^
/opt/boost-47/include/boost/mpl/at.hpp:32:7: note: in instantiation of template class
      'boost::mpl::at_impl<boost::fusion::fusion_sequence_tag>::apply<boost::fusion::vector<const mapnik::box2d<double> &,
      agg::rasterizer_outline_aa<agg::renderer_outline_aa<agg::renderer_base<agg::pixfmt_custom_blend_rgba<agg::comp_op_adaptor_rgba_pre<agg::rgba8,
      agg::order_rgba>, agg::row_ptr_cache<unsigned char> > > >, agg::line_coord> &, const mapnik::line_symbolizer &, const mapnik::CoordTransform
      &, const mapnik::proj_transform &, const agg::trans_affine &, double, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_>,
      mpl_::int_<0> >' requested here
    : at_impl< typename sequence_tag<Sequence>::type >
      ^
include/mapnik/vertex_converters.hpp:130:30: note: in instantiation of template class 'boost::mpl::at<boost::fusion::vector<const
      mapnik::box2d<double> &,
      agg::rasterizer_outline_aa<agg::renderer_outline_aa<agg::renderer_base<agg::pixfmt_custom_blend_rgba<agg::comp_op_adaptor_rgba_pre<agg::rgba8,
      agg::order_rgba>, agg::row_ptr_cache<unsigned char> > > >, agg::line_coord> &, const mapnik::line_symbolizer &, const mapnik::CoordTransform
      &, const mapnik::proj_transform &, const agg::trans_affine &, double, boost::fusion::void_, boost::fusion::void_, boost::fusion::void_>,
      mpl_::int_<0> >' requested here
        typename boost::mpl::at<Args,boost::mpl::int_<0> >::type box = boost::fusion::at_c<0>(args);
                             ^
i
```
