### ISSUE TITLE
Compatibility with Python>=3.10

### ISSUE THREAD

**Issue by frafra** [mapnik/mapnik#4412]
Cannot build using Python 3.10/3.11:

```python-traceback
Traceback (most recent call last):
  File "/go/mapnik-3.1.0/scons/scons.py", line 192, in <module>
    import SCons.Script
  File "/go/mapnik-3.1.0/scons/scons-local-3.0.1/SCons/Script/__init__.py", line 80, in <module>
    import SCons.Action
  File "/go/mapnik-3.1.0/scons/scons-local-3.0.1/SCons/Action.py", line 113, in <module>
    import SCons.Errors
  File "/go/mapnik-3.1.0/scons/scons-local-3.0.1/SCons/Errors.py", line 34, in <module>
    import SCons.Util
  File "/go/mapnik-3.1.0/scons/scons-local-3.0.1/SCons/Util.py", line 49, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
make: *** [Makefile:32: src/json/libmapnik-json.a] Error 1
```

See: https://stackoverflow.com/a/72032097/1312346.

**Comment by hummeltech** [comment]
A fix for this has been merged, however has not yet been included in a new release.

Here is the commit, in case that helps:
7da9009e7ffffb0b9429890f6f13fee837ac320f
