### ISSUE TITLE
json/feature_grammar.cpp doesn't compile with boost 1.46

### ISSUE THREAD

**Issue by lightmare** [mapnik/mapnik#1342]
Copied from:
https://github.com/mapnik/mapnik/commit/348dfff0c7cefd92ba5893583165ff6500eeb9c7#commitcomment-1621817
per Dane's request.

Instantiantions of this grammar were previously guarded by `#if BOOST_VERSION >= 104700`. I know you've moved to boost 1.47+, but we're going to stick with 1.46 for some time, as that is the version we currenty have on servers, and will probably only update when debian wheezy goes stable.

I had to change `%=` to `=`, otherwise I was getting error in `/usr/include/boost/variant/variant.hpp +1300 :9:
error: no matching function for call to
‘boost::variant<mapnik::value_null, bool, int, double>::initializer::initialize(void*, const boost::spirit::unused_type&)’`

``` diff
diff --git a/src/json/feature_grammar.cpp b/src/json/feature_grammar.cpp
index 59be938..8f5364e 100644
--- a/src/json/feature_grammar.cpp
+++ b/src/json/feature_grammar.cpp
@@ -82,11 +82,11 @@ feature_grammar<Iterator,FeatureType>::feature_grammar(mapnik::transcoder const&
         >> lit(']')
         ;

-    number %= strict_double
+    number = strict_double
         | int_
         | lit("true") [_val = true]
-        | lit ("false") [_val = false]
-        | lit("null")[_val = construct<value_null>()]
+        | lit("false") [_val = false]
+        | lit("null") [_val = construct<value_null>()]
         ;

     unesc_char.add
```
