### ISSUE TITLE
Fails to build with Boost 1.69 (develop snapshot)

### ISSUE THREAD

**Issue by jbeich** [mapnik/mapnik#4000]
After boostorg/gil@32fec9f05ba8 build fails. See [error log](https://ptpb.pw/WGgW).

```c++
In file included from src/save_map.cpp:40:
include/mapnik/image_filter.hpp:33:10: fatal error: 'boost/gil/gil_all.hpp' file not found
#include <boost/gil/gil_all.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
deps/agg/src/agg_pixfmt_rgba.cpp:6:10: fatal error: 'boost/gil/gil_all.hpp' file not found
#include <boost/gil/gil_all.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by artemp** [comment]
@jbeich  Thanks for reporting, fixed in bcb1e675075c64cb2c398de5013306b2b9cd47ce
